---
output:
  html_document:
    css: "leaflet_map.css"
params:
  add_popups: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(bcmaps)
library(sf)
library(dplyr)
library(rmapshaper)
library(mapview)
library(patchwork)
library(ggplot2)
library(purrr)
library(readr)

ecoreg_summary <- read_csv("out/data/ecoreg_summary.csv") %>% 
  filter(name != "Province", roaded_class == "Not Roaded") %>% 
  group_by(name) %>% 
  summarize(percent_unroaded = sum(percent_in_distance_class), 
            area_ha = sum(area_ha))

ecoreg <- ecoregions() %>% 
  filter(!ECOREGION_CODE %in% c("HCS", "IPS", "OPS", "SBC", "TPC")) %>% 
  ms_simplify() %>% 
  st_intersection(bc_bound()) %>% 
  st_transform(4326) %>% 
  group_by(ECOREGION_NAME) %>% 
  summarize() %>% 
  ms_simplify() %>% 
  left_join(ecoreg_summary, by = c("ECOREGION_NAME" = "name"))

if (params$add_popups) {
  # get plot_list with ecoregions in same order as ecoregions in ecoreg
  plot_list <- readRDS("tmp/plotlist.rds")[ecoreg$ECOREGION_NAME]
  
  popupGraph_list <- imap(plot_list, ~ {
    .x$barchart + .x$map +
      plot_layout(widths = c(1, 1.5)) +
      plot_annotation(title = tools::toTitleCase(tolower(.y)),
                      theme = theme(title = element_text(size = 18)))
  })
  
  popups <-  popupGraph(popupGraph_list, type = "svg", width = 700,
                        height = 400)
  popup_options <-  popupOptions(maxWidth = "100%", autoPan = TRUE,
                                 keepInView = TRUE,
                                 zoomAnimation = FALSE,
                                 closeOnClick = TRUE,
                                 autoPanPaddingTopLeft = c(120, 10),
                                 autoPanPaddingBottomRight = c(10,10))
} else {
  popups <- popup_options <- NULL
}
```


```{r labels-popups, include=FALSE}
labels <- sprintf(
  "<strong>%s (%1.1f%%)</strong>",
  tools::toTitleCase(tolower(ecoreg$ECOREGION_NAME)), 
  ecoreg$percent_unroaded
) %>% lapply(htmltools::HTML)

pal <- colorNumeric(palette = "YlGn", domain = ecoreg$percent_unroaded)
```

```{r leaflet-map, echo=FALSE}
leaflet(ecoreg, width = "900px", height = "550px") %>% 
  setView(lng = -126.5, lat = 54.5, zoom = 5) %>% 
  addProviderTiles("OpenStreetMap.BlackAndWhite", 
                   options = providerTileOptions(minZoom = 5, maxZoom = 10)) %>% 
  addPolygons(color = "#7f7f7f",
              fillColor = ~pal(percent_unroaded),
              weight = 1, fillOpacity = 0.6,
              highlightOptions = highlightOptions(fillOpacity = 0.9,
                                                  weight = 2,
                                                  bringToFront = TRUE), 
              label = labels,
              labelOptions = labelOptions(direction = "auto", 
                                          textsize = "12px"), 
              popup = popups, 
              popupOptions = popup_options
              ) %>% 
  addEasyButton(easyButton(
     icon = htmltools::span('Reset to B.C.'),
     onClick = JS("function(btn, map) { 
                     map.closePopup();
                     map.setView({lon: -126.5, lat: 54.5}, 5);
                  }"), 
     position = "bottomleft", id = "reset-button")) %>% 
  addLegend(position = "bottomleft", pal = pal, values = ~percent_unroaded, 
            title = htmltools::HTML("% Area Not<br/>Influenced<br/>by Roads"), 
            labFormat = labelFormat(suffix = "%", between = ""))
```
